service: whitelist

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  whitelist:
    handler: handler.whitelist
    events:
      - httpApi:
          path: /users/whitelist
          method: get
          cors: true
