service: whitelist

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 202012214

package:
  exclude:
    - venv/**

functions:
  whitelist:
    handler: handler.whitelist
    events:
      - httpApi:
          path: /users/whitelist
          method: get
          cors: true
